// This file is generated by Astro DB
declare module 'astro:db' {
	export const Radio: import("@astrojs/db/runtime").Table<
		"Radio",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Radio","primaryKey":true}},"title":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"title","collection":"Radio","primaryKey":false,"optional":false}},"thumbnail":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"thumbnail","collection":"Radio","primaryKey":false,"optional":false}},"genre":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"genre","collection":"Radio","primaryKey":false,"optional":false}}}
	>;
}
